# Generated by Django 3.2.9 on 2021-11-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timeStamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='value',
        ),
    ]
