# Generated by Django 3.2.9 on 2021-11-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20211123_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='toUser',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=10000),
        ),
    ]
